services:
  frontend:
    build: .
    command: npx ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
    restart: always

  api:
    image: clue/json-server
    ports:
      - "3000:80"
    volumes:
      - ./db.json:/data/db.json
    restart: always